

services:
  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: beads_nginx
    ports:
      - "80:80"
      - "445:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./backend/uploads:/app/backend/uploads:ro
      - ./backend/outputs:/app/backend/outputs:ro
    depends_on:
      - backend
    restart: unless-stopped
  beads_mysql:
    image: mysql:8.0
    container_name: beads_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 225291
      MYSQL_DATABASE: beads
      MYSQL_USER: beads_user
      MYSQL_PASSWORD: 225291
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      # 初始化脚本（启动时执行）
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./database/import_codes.sql:/docker-entrypoint-initdb.d/02-import_codes.sql:ro

      # ✅ 持久化 MySQL 数据到本地 ./database/data
      - ./database/data:/var/lib/mysql

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Flask 后端
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beads_backend
    expose:
      - "5001"
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/outputs:/app/backend/outputs
      - ./backend/temp_processing:/app/backend/temp_processing
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

